Add check for required commands during initialization

diff --git a/common/volntfy-d b/common/volntfy-d
--- a/common/volntfy-d
+++ b/common/volntfy-d
@@ -21,14 +21,36 @@ declare -r \
     MS_UNMUTE="unmute" \
     MS_MUTE="mute"
 
+check_command(){
+    cmd="$1"
+    pkg="$2"
+
+    command -v "${cmd}" >/dev/null 2>&1 || {
+        echo -e "${RED}${BOLD}ERROR"'!!'"${RESET} command ${BOLD}${cmd}${RESET} is missing." >&2
+        echo -e "Install ${BOLD}${pkg}${RESET} package, that provides it. Aborting." >&2
+        exit 1; 
+    }
+}
+
 check_prerequisites(){
     mkdir -p CONFIG_DIR || {
         echo -e "${RED}${BOLD}ERROR"'!!'"${RESET} Failed to create configuration directory. Aborting." >&2
         exit 1; 
     }
 
-    # TODO check if required commands exists
-    # local -ar commands=(volntfy pactl stdbuf flock)
+    # Check if required commands exists
+    local -Ar command_package=( 
+        [volntfy]="volctl" 
+        [pactl]="pulseaudio-utils" 
+        [stdbuf]="coreutils" 
+        [flock]="util-linux" 
+    )
+    for cmd in "${!command_package[@]}"
+    do
+        package="${command_package[${cmd}]}"
+        check_command "${cmd}" "${package}"
+    done
+
     # TODO check if notification server exists
 }
 
@@ -66,17 +88,6 @@ get_volume(){
 get_default_sink_index(){
     pactl list sinks | awk -W posix '/^Sink #/{gsub("#", ""); idx = $2}
         /^[ \t]+Name: / {insink = $2 == "'"$(pactl get-default-sink)"'"; if (insink) { print idx }; exit}'
-}
-
-check_command(){
-    cmd="$1"
-    pkg="$2"
-
-    command -v "${cmd}" >/dev/null 2>&1 || {
-        echo -e "${RED}${BOLD}ERROR"'!!'"${RESET} command ${BOLD}${cmd}${RESET} is missing." >&2
-        echo -e "Install ${BOLD}${pkg}${RESET} package, that provides it. Aborting." >&2
-        exit 1; 
-    }
 }
 
 play_volume_changed(){
